### ISSUE TITLE
Cleanup: remove Internal namespaces from API reference

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework.ApiDocs#10]
_From @divega on June 5, 2017 22:18_

E.g. https://docs.microsoft.com/en-us/ef/core/api/microsoft.entityframeworkcore.design.internal. 

_Copied from original issue: aspnet/EntityFramework.Docs#402_

**Comment by divega** [comment]
cc @dend

**Comment by dend** [comment]
@divega there is a way to filter those out. Will share on an internal thread after the holidays.

**Comment by dend** [comment]
This is now resolved.

**Comment by divega** [comment]
@dend I am reopening this. It seems it has regressed.

**Comment by divega** [comment]
@dend I still see lots of *.Internal namespaces in https://docs.microsoft.com/en-us/dotnet/api/?view=efcore-2.1.

**Comment by smitpatel** [comment]
This is no longer the case and should be closed.

**Comment by mairaw** [comment]
I still see them @smitpatel:
![image](https://user-images.githubusercontent.com/12971179/65471467-1ab88500-de24-11e9-81bb-5620565f5c2c.png)

**Comment by smitpatel** [comment]
I searched for .internal and it gave 0 results so I concluded it was corrected. My bad. What is the way to fix it? Re-generate the docs?

**Comment by mairaw** [comment]
You can just add the desired namespaces to this file similar to what was done to fix that for Microsoft.EntityFrameworkCore.Design.Internal: https://github.com/aspnet/EntityFramework.ApiDocs/blob/master/dotnet/xml/_filter.xml

**Comment by mairaw** [comment]
I'm assigning to myself.

**Comment by smitpatel** [comment]
@mairaw - When would this be on website? When does the tool run again to re-generate APIs?
